-- Cajas de las tiendas: cada caja se abre con un fondo, cobra las ventas de la tienda (efectivo,
-- Yape/Plin, tarjeta o transferencia), registra entradas, salidas y devoluciones de efectivo,
-- y se cierra contando el efectivo para ver si cuadra.
-- Los turnos, pagos y movimientos solo se escriben desde las funciones de abajo, que validan
-- permisos y ubicación; así nadie puede alterar el cuadre desde la API.
-- Se puede volver a ejecutar sin errores (no usa DROP).

-- ── Tablas ────────────────────────────────────────────────────────────────

create table if not exists public.cajas (
  id bigint generated by default as identity primary key,
  almacen_id bigint not null references public.almacenes (id),
  nombre text not null,
  activa boolean not null default true,
  creado_en timestamptz not null default now(),
  constraint cajas_nombre_largo check (char_length(btrim(nombre)) between 1 and 40)
);
create unique index if not exists cajas_nombre_unico on public.cajas (almacen_id, lower(btrim(nombre)));

create table if not exists public.caja_turnos (
  id bigint generated by default as identity primary key,
  caja_id bigint not null references public.cajas (id),
  almacen_id bigint not null references public.almacenes (id),
  estado text not null default 'abierta',
  abierta_por uuid not null references auth.users (id),
  abierta_por_nombre text,
  abierta_en timestamptz not null default now(),
  monto_inicial numeric(12, 2) not null,
  cerrada_por uuid references auth.users (id),
  cerrada_por_nombre text,
  cerrada_en timestamptz,
  efectivo_esperado numeric(12, 2),
  efectivo_contado numeric(12, 2),
  diferencia numeric(12, 2),
  conteo jsonb,
  nota_cierre text,
  constraint caja_turnos_estado check (estado in ('abierta', 'cerrada')),
  constraint caja_turnos_cierre check ((estado = 'abierta') = (cerrada_en is null)),
  constraint caja_turnos_montos check (monto_inicial >= 0 and (efectivo_contado is null or efectivo_contado >= 0)),
  constraint caja_turnos_nota check (nota_cierre is null or char_length(nota_cierre) <= 300)
);
-- Una caja no puede estar abierta dos veces, y cada persona tiene como máximo una caja abierta.
create unique index if not exists caja_turnos_una_abierta on public.caja_turnos (caja_id) where estado = 'abierta';
create unique index if not exists caja_turnos_usuario_abierta on public.caja_turnos (abierta_por) where estado = 'abierta';
create index if not exists caja_turnos_almacen on public.caja_turnos (almacen_id, abierta_en desc);

alter table public.ventas add column if not exists turno_id bigint references public.caja_turnos (id);
create index if not exists ventas_turno on public.ventas (turno_id) where turno_id is not null;

create table if not exists public.venta_pagos (
  id bigint generated by default as identity primary key,
  venta_id bigint not null references public.ventas (id) on delete cascade,
  turno_id bigint references public.caja_turnos (id),
  metodo text not null,
  monto numeric(12, 2) not null,
  operacion text,
  creado_en timestamptz not null default now(),
  constraint venta_pagos_metodo check (metodo in ('efectivo', 'yape_plin', 'tarjeta', 'transferencia')),
  constraint venta_pagos_monto check (monto > 0),
  constraint venta_pagos_operacion check (operacion is null or char_length(operacion) <= 40)
);
create index if not exists venta_pagos_venta on public.venta_pagos (venta_id);
create index if not exists venta_pagos_turno on public.venta_pagos (turno_id) where turno_id is not null;

create table if not exists public.caja_movimientos (
  id bigint generated by default as identity primary key,
  turno_id bigint not null references public.caja_turnos (id),
  tipo text not null,
  monto numeric(12, 2) not null,
  motivo text not null,
  venta_id bigint references public.ventas (id),
  registrado_por uuid references auth.users (id),
  registrado_por_nombre text,
  creado_en timestamptz not null default now(),
  constraint caja_movimientos_tipo check (tipo in ('entrada', 'salida', 'devolucion')),
  constraint caja_movimientos_monto check (monto > 0),
  constraint caja_movimientos_motivo check (char_length(btrim(motivo)) between 1 and 160)
);
create index if not exists caja_movimientos_turno on public.caja_movimientos (turno_id);
create index if not exists caja_movimientos_venta on public.caja_movimientos (venta_id) where venta_id is not null;

-- ── Permisos de lectura (RLS) ────────────────────────────────────────────

alter table public.cajas enable row level security;
alter table public.caja_turnos enable row level security;
alter table public.venta_pagos enable row level security;
alter table public.caja_movimientos enable row level security;

do $$ begin
  if not exists (select 1 from pg_policies where policyname = 'cajas_leer' and tablename = 'cajas') then
    create policy cajas_leer on public.cajas for select to authenticated
      using ((select public.puede_acceder())
             and ((select public.ubicacion_restringida()) is null or almacen_id = (select public.ubicacion_restringida())));
  end if;
  -- Las cajas se crean y se renombran desde la app (quien administra Almacenes); solo en tiendas.
  if not exists (select 1 from pg_policies where policyname = 'cajas_crear' and tablename = 'cajas') then
    create policy cajas_crear on public.cajas for insert to authenticated
      with check ((select public.tiene_permiso('almacenes'))
                  and exists (select 1 from public.almacenes a where a.id = almacen_id and a.tipo = 'tienda'));
  end if;
  if not exists (select 1 from pg_policies where policyname = 'cajas_editar' and tablename = 'cajas') then
    create policy cajas_editar on public.cajas for update to authenticated
      using ((select public.tiene_permiso('almacenes')))
      with check ((select public.tiene_permiso('almacenes')));
  end if;
  if not exists (select 1 from pg_policies where policyname = 'caja_turnos_leer' and tablename = 'caja_turnos') then
    create policy caja_turnos_leer on public.caja_turnos for select to authenticated
      using ((select public.puede_ver('{ventas,dashboard,reportes}'::text[]))
             and ((select public.ubicacion_restringida()) is null or almacen_id = (select public.ubicacion_restringida())));
  end if;
  -- Pagos y movimientos se ven si se ve la venta o el turno (las políticas de esas tablas se aplican).
  if not exists (select 1 from pg_policies where policyname = 'venta_pagos_leer' and tablename = 'venta_pagos') then
    create policy venta_pagos_leer on public.venta_pagos for select to authenticated
      using (exists (select 1 from public.ventas v where v.id = venta_id));
  end if;
  if not exists (select 1 from pg_policies where policyname = 'caja_movimientos_leer' and tablename = 'caja_movimientos') then
    create policy caja_movimientos_leer on public.caja_movimientos for select to authenticated
      using (exists (select 1 from public.caja_turnos t where t.id = turno_id));
  end if;
end $$;

revoke all on public.cajas, public.caja_turnos, public.venta_pagos, public.caja_movimientos from anon, authenticated;
grant select on public.cajas, public.caja_turnos, public.venta_pagos, public.caja_movimientos to authenticated;
grant insert (almacen_id, nombre) on public.cajas to authenticated;
grant update (nombre, activa) on public.cajas to authenticated;

-- Cada cambio queda en el Registro del sistema
create or replace trigger auditar_cajas after insert or update on public.cajas
  for each row execute function public.auditar_cambio();
create or replace trigger auditar_caja_turnos after insert or update on public.caja_turnos
  for each row execute function public.auditar_cambio();
create or replace trigger auditar_caja_movimientos after insert on public.caja_movimientos
  for each row execute function public.auditar_cambio();
create or replace trigger auditar_venta_pagos after insert on public.venta_pagos
  for each row execute function public.auditar_cambio();

-- ── Funciones internas ───────────────────────────────────────────────────

-- Efectivo que debería haber en la caja: fondo + cobros en efectivo + entradas − salidas − devoluciones.
create or replace function public.caja_efectivo_esperado(p_turno bigint)
returns numeric
language sql
stable
security definer
set search_path = ''
as $$
  select t.monto_inicial
    + coalesce((select sum(p.monto) from public.venta_pagos p where p.turno_id = t.id and p.metodo = 'efectivo'), 0)
    + coalesce((select sum(m.monto) from public.caja_movimientos m where m.turno_id = t.id and m.tipo = 'entrada'), 0)
    - coalesce((select sum(m.monto) from public.caja_movimientos m where m.turno_id = t.id and m.tipo in ('salida', 'devolucion')), 0)
  from public.caja_turnos t where t.id = p_turno;
$$;
revoke execute on function public.caja_efectivo_esperado(bigint) from public, anon, authenticated;

create or replace function public.caja_nombre_usuario()
returns text
language sql
stable
security definer
set search_path = ''
as $$ select coalesce((select p.nombre from public.perfiles p where p.id = (select auth.uid())), 'Usuario'); $$;
revoke execute on function public.caja_nombre_usuario() from public, anon, authenticated;

-- ── Abrir caja ───────────────────────────────────────────────────────────

create or replace function public.abrir_caja(p_caja_id bigint, p_monto_inicial numeric)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_caja record;
  v_ubic bigint := public.ubicacion_restringida();
  v_otro record;
  v_id bigint;
begin
  if not public.tiene_permiso('ventas') then
    raise exception 'No tienes permiso para abrir cajas' using errcode = '42501';
  end if;
  select c.*, a.nombre as tienda, a.tipo, a.activo as tienda_activa into v_caja
    from public.cajas c join public.almacenes a on a.id = c.almacen_id where c.id = p_caja_id;
  if not found then raise exception 'La caja no existe' using errcode = 'P0002'; end if;
  if v_ubic is not null and v_caja.almacen_id <> v_ubic then
    raise exception 'Solo puedes abrir cajas de tu tienda' using errcode = '42501';
  end if;
  if not v_caja.activa or not v_caja.tienda_activa or v_caja.tipo <> 'tienda' then
    raise exception 'La caja % no está disponible', v_caja.nombre using errcode = '22023';
  end if;
  if p_monto_inicial is null or p_monto_inicial < 0 or p_monto_inicial > 100000 then
    raise exception 'El fondo inicial debe ser un monto entre S/ 0 y S/ 100,000' using errcode = '22023';
  end if;

  select t.id, c.nombre as caja, a.nombre as tienda into v_otro
    from public.caja_turnos t join public.cajas c on c.id = t.caja_id join public.almacenes a on a.id = t.almacen_id
    where t.abierta_por = (select auth.uid()) and t.estado = 'abierta';
  if found then
    raise exception 'Ya tienes abierta la % de %. Ciérrala antes de abrir otra.', v_otro.caja, v_otro.tienda using errcode = '23505';
  end if;
  select t.abierta_por_nombre into v_otro from public.caja_turnos t where t.caja_id = p_caja_id and t.estado = 'abierta';
  if found then
    raise exception 'La % ya está abierta por %.', v_caja.nombre, coalesce(v_otro.abierta_por_nombre, 'otra persona') using errcode = '23505';
  end if;

  insert into public.caja_turnos (caja_id, almacen_id, abierta_por, abierta_por_nombre, monto_inicial)
  values (p_caja_id, v_caja.almacen_id, (select auth.uid()), public.caja_nombre_usuario(), round(p_monto_inicial, 2))
  returning id into v_id;
  return jsonb_build_object('turno_id', v_id, 'caja', v_caja.nombre, 'tienda', v_caja.tienda);
end $$;

-- ── Turno abierto: comprobación común ────────────────────────────────────

create or replace function public.caja_turno_operable(p_turno bigint, p_accion text)
returns public.caja_turnos
language plpgsql
security definer
set search_path = ''
as $$
declare
  v public.caja_turnos;
  v_ubic bigint := public.ubicacion_restringida();
  v_rol text := public.rol_actual();
begin
  if not public.tiene_permiso('ventas') then
    raise exception 'No tienes permiso para %', p_accion using errcode = '42501';
  end if;
  select * into v from public.caja_turnos where id = p_turno for update;
  if not found then raise exception 'La caja no existe' using errcode = 'P0002'; end if;
  if v_ubic is not null and v.almacen_id <> v_ubic then
    raise exception 'Esa caja es de otra tienda' using errcode = '42501';
  end if;
  if v.estado <> 'abierta' then
    raise exception 'La caja ya está cerrada' using errcode = '22023';
  end if;
  -- Solo quien la abrió, o un administrador o gerente, opera la caja
  if v.abierta_por <> (select auth.uid()) and coalesce(v_rol, '') not in ('administrador', 'gerente') then
    raise exception 'Esta caja la abrió %; solo esa persona o un administrador puede %', coalesce(v.abierta_por_nombre, 'otra persona'), p_accion
      using errcode = '42501';
  end if;
  return v;
end $$;
revoke execute on function public.caja_turno_operable(bigint, text) from public, anon, authenticated;

-- ── Entradas y salidas de efectivo ──────────────────────────────────────

create or replace function public.registrar_movimiento_caja(p_turno_id bigint, p_tipo text, p_monto numeric, p_motivo text)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v public.caja_turnos;
  v_disp numeric;
  v_id bigint;
begin
  v := public.caja_turno_operable(p_turno_id, 'registrar movimientos');
  if p_tipo not in ('entrada', 'salida') then
    raise exception 'El movimiento debe ser una entrada o una salida' using errcode = '22023';
  end if;
  if p_monto is null or p_monto <= 0 or p_monto > 100000 then
    raise exception 'Ingresa un monto mayor que cero' using errcode = '22023';
  end if;
  if char_length(btrim(coalesce(p_motivo, ''))) = 0 then
    raise exception 'Escribe el motivo del movimiento' using errcode = '22023';
  end if;
  if p_tipo = 'salida' then
    v_disp := public.caja_efectivo_esperado(p_turno_id);
    if round(p_monto, 2) > v_disp then
      raise exception 'En la caja hay S/ %; no alcanza para sacar S/ %', to_char(v_disp, 'FM999G999G990D00'), to_char(p_monto, 'FM999G999G990D00')
        using errcode = '22023';
    end if;
  end if;
  insert into public.caja_movimientos (turno_id, tipo, monto, motivo, registrado_por, registrado_por_nombre)
  values (p_turno_id, p_tipo, round(p_monto, 2), left(btrim(p_motivo), 160), (select auth.uid()), public.caja_nombre_usuario())
  returning id into v_id;
  return jsonb_build_object('id', v_id, 'efectivo_esperado', public.caja_efectivo_esperado(p_turno_id));
end $$;

-- ── Resumen del turno (para la pantalla y el ticket) ─────────────────────

create or replace function public.resumen_turno(p_turno_id bigint)
returns jsonb
language plpgsql
stable
security definer
set search_path = ''
as $$
declare
  v record;
  v_ubic bigint := public.ubicacion_restringida();
begin
  if not public.puede_ver('{ventas,dashboard,reportes}'::text[]) then
    raise exception 'No tienes permiso para ver las cajas' using errcode = '42501';
  end if;
  select t.*, c.nombre as caja, a.nombre as tienda into v
    from public.caja_turnos t join public.cajas c on c.id = t.caja_id join public.almacenes a on a.id = t.almacen_id
    where t.id = p_turno_id;
  if not found then raise exception 'La caja no existe' using errcode = 'P0002'; end if;
  if v_ubic is not null and v.almacen_id <> v_ubic then
    raise exception 'Esa caja es de otra tienda' using errcode = '42501';
  end if;
  return jsonb_build_object(
    'turno_id', v.id, 'caja_id', v.caja_id, 'caja', v.caja, 'tienda', v.tienda, 'almacen_id', v.almacen_id,
    'estado', v.estado, 'abierta_por', v.abierta_por, 'abierta_por_nombre', v.abierta_por_nombre, 'abierta_en', v.abierta_en,
    'cerrada_por_nombre', v.cerrada_por_nombre, 'cerrada_en', v.cerrada_en,
    'monto_inicial', v.monto_inicial,
    'pagos', coalesce((select jsonb_object_agg(metodo, jsonb_build_object('monto', total, 'cantidad', n))
                        from (select p.metodo, sum(p.monto) total, count(distinct p.venta_id) n
                              from public.venta_pagos p where p.turno_id = v.id group by p.metodo) x), '{}'::jsonb),
    'ventas', (select count(*) from public.ventas ve where ve.turno_id = v.id),
    'entradas', coalesce((select sum(m.monto) from public.caja_movimientos m where m.turno_id = v.id and m.tipo = 'entrada'), 0),
    'salidas', coalesce((select sum(m.monto) from public.caja_movimientos m where m.turno_id = v.id and m.tipo = 'salida'), 0),
    'devoluciones', coalesce((select sum(m.monto) from public.caja_movimientos m where m.turno_id = v.id and m.tipo = 'devolucion'), 0),
    'efectivo_esperado', case when v.estado = 'cerrada' then v.efectivo_esperado else public.caja_efectivo_esperado(v.id) end,
    'efectivo_contado', v.efectivo_contado, 'diferencia', v.diferencia, 'conteo', v.conteo, 'nota_cierre', v.nota_cierre,
    'movimientos', coalesce((select jsonb_agg(jsonb_build_object('tipo', m.tipo, 'monto', m.monto, 'motivo', m.motivo,
                              'quien', m.registrado_por_nombre, 'en', m.creado_en) order by m.creado_en)
                             from public.caja_movimientos m where m.turno_id = v.id), '[]'::jsonb)
  );
end $$;

-- ── Cerrar caja (arqueo) ─────────────────────────────────────────────────

create or replace function public.cerrar_caja(p_turno_id bigint, p_conteo jsonb, p_nota text)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v public.caja_turnos;
  v_den text;
  v_cant numeric;
  v_contado numeric := 0;
  v_esperado numeric;
  v_validas text[] := array['200', '100', '50', '20', '10', '5', '2', '1', '0.50', '0.20', '0.10'];
begin
  v := public.caja_turno_operable(p_turno_id, 'cerrar la caja');
  if p_conteo is null or jsonb_typeof(p_conteo) <> 'object' then
    raise exception 'Cuenta el efectivo antes de cerrar la caja' using errcode = '22023';
  end if;
  for v_den, v_cant in select key, (value #>> '{}')::numeric from jsonb_each(p_conteo) loop
    if not (v_den = any (v_validas)) then
      raise exception 'Denominación no válida: %', v_den using errcode = '22023';
    end if;
    if v_cant is null or v_cant < 0 or v_cant <> trunc(v_cant) or v_cant > 100000 then
      raise exception 'La cantidad de billetes o monedas de S/ % no es válida', v_den using errcode = '22023';
    end if;
    v_contado := v_contado + v_den::numeric * v_cant;
  end loop;
  v_esperado := public.caja_efectivo_esperado(p_turno_id);
  update public.caja_turnos set
    estado = 'cerrada', cerrada_por = (select auth.uid()), cerrada_por_nombre = public.caja_nombre_usuario(), cerrada_en = now(),
    efectivo_esperado = v_esperado, efectivo_contado = round(v_contado, 2), diferencia = round(v_contado - v_esperado, 2),
    conteo = p_conteo, nota_cierre = nullif(left(btrim(coalesce(p_nota, '')), 300), '')
  where id = p_turno_id;
  return public.resumen_turno(p_turno_id);
end $$;

-- ── Devolver o anular una venta ──────────────────────────────────────────
-- Devuelve el stock a la ubicación de la venta. Si se cobró en efectivo en una tienda,
-- saca ese efectivo de la caja abierta que se indique.

create or replace function public.devolver_venta(p_venta_id bigint, p_estado text, p_turno_id bigint, p_motivo text)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v record;
  v_ubic bigint := public.ubicacion_restringida();
  v_efectivo numeric;
  v_otros numeric;
  v_turno public.caja_turnos;
  v_disp numeric;
  it record;
begin
  if not public.tiene_permiso('ventas') then
    raise exception 'No tienes permiso para devolver ventas' using errcode = '42501';
  end if;
  if p_estado not in ('Devuelta', 'Cancelada') then
    raise exception 'El estado debe ser Devuelta o Cancelada' using errcode = '22023';
  end if;
  select ve.*, a.tipo as tipo_almacen into v
    from public.ventas ve left join public.almacenes a on a.id = ve.almacen_id where ve.id = p_venta_id for update of ve;
  if not found then raise exception 'La venta no existe' using errcode = 'P0002'; end if;
  if v_ubic is not null and coalesce(v.almacen_id, -1) <> v_ubic then
    raise exception 'Esa venta es de otra ubicación' using errcode = '42501';
  end if;
  if v.estado in ('Devuelta', 'Cancelada') then
    raise exception 'La venta % ya está %', v.codigo, lower(v.estado) using errcode = '22023';
  end if;

  select coalesce(sum(monto) filter (where metodo = 'efectivo'), 0), coalesce(sum(monto) filter (where metodo <> 'efectivo'), 0)
    into v_efectivo, v_otros from public.venta_pagos where venta_id = p_venta_id;

  if v_efectivo > 0 and v.tipo_almacen = 'tienda' then
    if p_turno_id is null then
      raise exception 'Abre tu caja para devolver S/ % en efectivo', to_char(v_efectivo, 'FM999G999G990D00') using errcode = '22023';
    end if;
    v_turno := public.caja_turno_operable(p_turno_id, 'devolver efectivo');
    if v_turno.almacen_id <> v.almacen_id then
      raise exception 'El efectivo se devuelve desde una caja de la misma tienda de la venta' using errcode = '22023';
    end if;
    v_disp := public.caja_efectivo_esperado(p_turno_id);
    if v_efectivo > v_disp then
      raise exception 'En la caja hay S/ %; no alcanza para devolver S/ %', to_char(v_disp, 'FM999G999G990D00'), to_char(v_efectivo, 'FM999G999G990D00')
        using errcode = '22023';
    end if;
    insert into public.caja_movimientos (turno_id, tipo, monto, motivo, venta_id, registrado_por, registrado_por_nombre)
    values (p_turno_id, 'devolucion', v_efectivo,
            left(case p_estado when 'Devuelta' then 'Devolución de ' else 'Anulación de ' end || v.codigo
                 || coalesce(': ' || nullif(btrim(p_motivo), ''), ''), 160),
            p_venta_id, (select auth.uid()), public.caja_nombre_usuario());
  end if;

  -- El stock vuelve a la ubicación de donde salió
  if v.almacen_id is not null then
    for it in select producto_id, talla, sum(cantidad) as cantidad from public.venta_items where venta_id = p_venta_id group by 1, 2 loop
      insert into public.inventario (producto_id, talla, almacen_id, cantidad)
      values (it.producto_id, it.talla, v.almacen_id, it.cantidad)
      on conflict (producto_id, talla, almacen_id) do update set cantidad = public.inventario.cantidad + excluded.cantidad;
    end loop;
  end if;

  update public.ventas set estado = p_estado where id = p_venta_id;
  return jsonb_build_object('codigo', v.codigo, 'estado', p_estado, 'efectivo_devuelto',
                            case when v.tipo_almacen = 'tienda' then v_efectivo else 0 end,
                            'otros_medios', v_otros + case when v.tipo_almacen = 'tienda' then 0 else v_efectivo end);
end $$;

-- ── Registrar venta (con pagos y caja) ───────────────────────────────────
-- Pasa a SECURITY DEFINER con la ubicación validada aquí mismo. Así el correlativo V-0001
-- se calcula sobre todas las ventas (antes, con la vista limitada de una tienda, podía repetirse).

create or replace function public.registrar_venta(p jsonb)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_clave   uuid   := nullif(p->>'clave', '')::uuid;
  v_nombre  text   := btrim(coalesce(p->>'cliente_nombre', ''));
  v_tel     text   := nullif(btrim(coalesce(p->>'cliente_telefono', '')), '');
  v_almacen bigint := nullif(p->>'almacen_id', '')::bigint;
  v_canal   bigint := nullif(p->>'canal_id', '')::bigint;
  v_estado  text   := coalesce(nullif(p->>'estado', ''), 'Pendiente');
  v_items   jsonb  := coalesce(p->'items', '[]'::jsonb);
  v_pagos   jsonb  := coalesce(p->'pagos', '[]'::jsonb);
  v_turno   bigint := nullif(p->>'turno_id', '')::bigint;
  v_ubic    bigint := public.ubicacion_restringida();
  v_tipo    text;
  v_t       public.caja_turnos;
  v_pagado  numeric;
  v_cliente bigint;
  v_prev    record;
  r         record;
  v_stock   integer;
  v_prod    text;
  v_total   numeric;
  v_num     integer;
  v_codigo  text;
  v_venta   bigint;
begin
  if not public.tiene_permiso('ventas') then
    raise exception 'No tienes permiso para registrar ventas' using errcode = '42501';
  end if;
  if v_nombre = '' then raise exception 'Ingresa el nombre del cliente' using errcode = '22023'; end if;
  if v_almacen is null then raise exception 'Selecciona un almacén' using errcode = '22023'; end if;
  select a.tipo into v_tipo from public.almacenes a where a.id = v_almacen and a.activo;
  if not found then raise exception 'La ubicación elegida no existe o está desactivada' using errcode = '22023'; end if;
  if v_ubic is not null and v_almacen <> v_ubic then
    raise exception 'Solo puedes vender desde tu ubicación' using errcode = '42501';
  end if;
  if v_estado not in ('Completada', 'Pendiente') then
    raise exception 'Una venta nueva solo puede estar Completada o Pendiente' using errcode = '22023';
  end if;
  if jsonb_typeof(v_items) <> 'array' or jsonb_array_length(v_items) = 0 then
    raise exception 'Agrega al menos un producto con cantidad válida' using errcode = '22023';
  end if;
  if exists (select 1 from jsonb_array_elements(v_items) e
             where coalesce((e->>'cantidad')::int, 0) <= 0 or (e->>'producto_id') is null
                or coalesce((e->>'precio_unitario')::numeric, -1) < 0) then
    raise exception 'Hay productos con cantidad o precio no válidos' using errcode = '22023';
  end if;
  if jsonb_typeof(v_pagos) <> 'array' then
    raise exception 'Los pagos no son válidos' using errcode = '22023';
  end if;
  if exists (select 1 from jsonb_array_elements(v_pagos) e
             where coalesce(e->>'metodo', '') not in ('efectivo', 'yape_plin', 'tarjeta', 'transferencia')
                or coalesce((e->>'monto')::numeric, 0) <= 0
                or char_length(coalesce(e->>'operacion', '')) > 40) then
    raise exception 'Hay pagos con medio o monto no válidos' using errcode = '22023';
  end if;

  -- Idempotencia: si esta clave ya se procesó, devolver la venta existente.
  if v_clave is not null then
    perform pg_advisory_xact_lock(hashtext('venta:' || v_clave::text));
    select id, codigo, total into v_prev from public.ventas where clave_idempotencia = v_clave;
    if found then
      return jsonb_build_object('id', v_prev.id, 'codigo', v_prev.codigo, 'total', v_prev.total, 'ya_procesada', true);
    end if;
  end if;

  select sum((e->>'cantidad')::int * (e->>'precio_unitario')::numeric) into v_total from jsonb_array_elements(v_items) e;
  select coalesce(sum(round((e->>'monto')::numeric, 2)), 0) into v_pagado from jsonb_array_elements(v_pagos) e;

  -- En una tienda la venta se cobra completa en una caja abierta de esa tienda.
  if v_tipo = 'tienda' then
    if v_turno is null then
      raise exception 'Abre una caja en esta tienda para registrar la venta' using errcode = '22023';
    end if;
    select * into v_t from public.caja_turnos where id = v_turno for update;
    if not found or v_t.estado <> 'abierta' then
      raise exception 'La caja elegida ya está cerrada; abre una caja para vender' using errcode = '22023';
    end if;
    if v_t.almacen_id <> v_almacen then
      raise exception 'La caja elegida es de otra tienda' using errcode = '22023';
    end if;
    if round(v_pagado, 2) <> round(v_total, 2) then
      raise exception 'El pago (S/ %) no coincide con el total (S/ %)', to_char(v_pagado, 'FM999G999G990D00'), to_char(v_total, 'FM999G999G990D00')
        using errcode = '22023';
    end if;
  else
    v_turno := null;
    if round(v_pagado, 2) > round(v_total, 2) then
      raise exception 'Lo pagado (S/ %) es mayor que el total (S/ %)', to_char(v_pagado, 'FM999G999G990D00'), to_char(v_total, 'FM999G999G990D00')
        using errcode = '22023';
    end if;
  end if;

  -- Stock: se bloquean las filas y se valida con el valor real (no con el de la pantalla).
  for r in
    select (e->>'producto_id')::bigint as producto_id, e->>'talla' as talla, sum((e->>'cantidad')::int) as cantidad
    from jsonb_array_elements(v_items) e group by 1, 2
  loop
    select i.cantidad into v_stock from public.inventario i
      where i.producto_id = r.producto_id and i.talla = r.talla and i.almacen_id = v_almacen
      for update;
    if coalesce(v_stock, 0) < r.cantidad then
      select nombre into v_prod from public.productos where id = r.producto_id;
      raise exception 'Stock insuficiente de % talla % (disponible: %)', coalesce(v_prod, 'producto'), r.talla, coalesce(v_stock, 0)
        using errcode = 'P0001';
    end if;
  end loop;

  -- Cliente: por teléfono, luego por nombre; si no existe, se crea (igual que antes).
  if v_tel is not null then
    select id into v_cliente from public.clientes where telefono = v_tel order by id limit 1;
  end if;
  if v_cliente is null then
    select id into v_cliente from public.clientes where nombre = v_nombre order by id limit 1;
  end if;
  if v_cliente is null then
    insert into public.clientes (nombre, telefono) values (v_nombre, v_tel) returning id into v_cliente;
  end if;

  -- Código correlativo sin repetidos (bloqueo mientras se asigna).
  perform pg_advisory_xact_lock(hashtext('ventas_codigo'));
  select coalesce(max(substring(codigo from '^V-(\d+)$')::int), 0) + 1 into v_num from public.ventas;
  v_codigo := 'V-' || lpad(v_num::text, 4, '0');

  insert into public.ventas (codigo, cliente_id, canal_id, almacen_id, estado, total, registrado_por, clave_idempotencia, turno_id)
  values (v_codigo, v_cliente, v_canal, v_almacen, v_estado, v_total, (select auth.uid()), v_clave, v_turno)
  returning id into v_venta;

  insert into public.venta_items (venta_id, producto_id, talla, cantidad, precio_unitario)
  select v_venta, (e->>'producto_id')::bigint, e->>'talla', (e->>'cantidad')::int, (e->>'precio_unitario')::numeric
  from jsonb_array_elements(v_items) e;

  insert into public.venta_pagos (venta_id, turno_id, metodo, monto, operacion)
  select v_venta, v_turno, e->>'metodo', round((e->>'monto')::numeric, 2), nullif(btrim(coalesce(e->>'operacion', '')), '')
  from jsonb_array_elements(v_pagos) e;

  for r in
    select (e->>'producto_id')::bigint as producto_id, e->>'talla' as talla, sum((e->>'cantidad')::int) as cantidad
    from jsonb_array_elements(v_items) e group by 1, 2
  loop
    update public.inventario set cantidad = cantidad - r.cantidad
      where producto_id = r.producto_id and talla = r.talla and almacen_id = v_almacen;
  end loop;

  return jsonb_build_object('id', v_venta, 'codigo', v_codigo, 'total', v_total, 'pagado', v_pagado, 'ya_procesada', false);
end $$;

-- Solo usuarios con sesión pueden llamar a las funciones de caja
revoke execute on function public.abrir_caja(bigint, numeric) from public, anon;
revoke execute on function public.registrar_movimiento_caja(bigint, text, numeric, text) from public, anon;
revoke execute on function public.resumen_turno(bigint) from public, anon;
revoke execute on function public.cerrar_caja(bigint, jsonb, text) from public, anon;
revoke execute on function public.devolver_venta(bigint, text, bigint, text) from public, anon;
revoke execute on function public.registrar_venta(jsonb) from public, anon;
grant execute on function public.abrir_caja(bigint, numeric) to authenticated;
grant execute on function public.registrar_movimiento_caja(bigint, text, numeric, text) to authenticated;
grant execute on function public.resumen_turno(bigint) to authenticated;
grant execute on function public.cerrar_caja(bigint, jsonb, text) to authenticated;
grant execute on function public.devolver_venta(bigint, text, bigint, text) to authenticated;
grant execute on function public.registrar_venta(jsonb) to authenticated;
